export enum ECouponStatus {
  PENDING = 'PENDING',
  ISSUED = 'ISSUED',
  PENDING_ATTESTATION = 'PENDING_ATTESTATION',
  ATTESTED = 'ATTESTED',
  CLAIM_SUBMITTED = 'CLAIM_SUBMITTED',
  CLAIMED = 'CLAIMED',
  EXPIRED = 'EXPIRED',
  ORPHANED = 'ORPHANED',
  REJECTED = 'REJECTED',
}
