export enum EErrorCodes {
  // Auth errors
  INVALID_GOOGLE_TOKEN = 'INVALID_GOOGLE_TOKEN',
  GOOGLE_UNAVAILABLE = 'GOOGLE_UNAVAILABLE',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
}
