export enum EErrorCodes {
  // Common errors
  INVALID_REQUEST = 'INVALID_REQUEST',

  ADMIN_KEY_INVALID = 'ADMIN_KEY_INVALID',

  // Merchants
  MERCHANT_NOT_FOUND = 'MERCHANT_NOT_FOUND',
  MERCHANT_ALREADY_REGISTERED = 'MERCHANT_ALREADY_REGISTERED',
  INVALID_MERCHANT_ADDRESS = 'INVALID_MERCHANT_ADDRESS',

  // Auth errors
  INVALID_GOOGLE_TOKEN = 'INVALID_GOOGLE_TOKEN',
  GOOGLE_UNAVAILABLE = 'GOOGLE_UNAVAILABLE',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  // Coupons & claims
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_NOT_CLAIMABLE = 'COUPON_NOT_CLAIMABLE',
  CLAIM_NOT_FOUND = 'CLAIM_NOT_FOUND',
  CLAIM_COOLDOWN = 'CLAIM_COOLDOWN',
  WALLET_NOT_LINKED = 'WALLET_NOT_LINKED',
  CHALLENGE_INVALID = 'CHALLENGE_INVALID',
  OWNERSHIP_PROOF_INVALID = 'OWNERSHIP_PROOF_INVALID',

  // Secrets
  SECRET_NOT_FOUND = 'SECRET_NOT_FOUND',
  WEAK_KDF_PARAMS = 'WEAK_KDF_PARAMS',
  INVALID_BLOB_SIZE = 'INVALID_BLOB_SIZE',
  WALLET_ADDRESS_MISMATCH = 'WALLET_ADDRESS_MISMATCH',

  // Transactions
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  WALLET_MISMATCH = 'WALLET_MISMATCH',
  INVALID_TX_HASH = 'INVALID_TX_HASH',
  UNSUPPORTED_CHAIN = 'UNSUPPORTED_CHAIN',
  INVALID_CURSOR = 'INVALID_CURSOR',

  // Idempotency
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',

  // Indexer
  INDEXER_RATE_LIMITED = 'INDEXER_RATE_LIMITED',
  INDEXER_UNAVAILABLE = 'INDEXER_UNAVAILABLE',
  INDEXER_REQUEST_FAILED = 'INDEXER_REQUEST_FAILED',
}
