export enum EErrorCodes {
  // Common errors
  INVALID_REQUEST = 'INVALID_REQUEST',

  // Auth errors
  INVALID_GOOGLE_TOKEN = 'INVALID_GOOGLE_TOKEN',
  GOOGLE_UNAVAILABLE = 'GOOGLE_UNAVAILABLE',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  // Coupons & claims
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_NOT_CLAIMABLE = 'COUPON_NOT_CLAIMABLE',
  CLAIM_NOT_FOUND = 'CLAIM_NOT_FOUND',
  CLAIM_COOLDOWN = 'CLAIM_COOLDOWN',
  WALLET_NOT_LINKED = 'WALLET_NOT_LINKED',

  // Idempotency
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',
}
